# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install s3p-sdk
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build config
      run: |
        python -c "import json; from config import config; print(json.dumps(config.dict()))" > config.json
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v$(date +'%Y.%m.%d.%H.%M.%S')"
        release_name: Release ${{ github.ref }}
        body: |
          Autogenerated release ${{ github.ref }}
          - Config file was generated
        draft: false
        prerelease: false
    - name: Upload config.json to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./config.json
        asset_name: config.json
        asset_content_type: application/json