# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.5"
    - name: Get latest tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "Latest tag: $latest_tag"

    - name: Increment tag version
      run: |
        IFS='.' read -r -a tag_parts <<< "$latest_tag"
        new_tag_version="${tag_parts[0]}.${tag_parts[1]}.${tag_parts[2] + 1}"
        echo "New tag version: $new_tag_version"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install s3p-sdk
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build config
      run: |
        python -c "import json; from config import config; print(json.dumps(config.dict()))" > config.json
    - name: Upload config.json as artifact
      uses: actions/upload-artifact@v2
      with:
        name: config
        path: config.json
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: $new_tag_version
          release_name: Autogenerated Release ${{ github.ref }}
          body: |
            Autogenerated release ${{ github.ref }}
            - Config file was generated
          draft: false
          prerelease: false
          assets: "config.json"
