name: Sync plugin to S3

on:
   release:
     types: [published]

env:
  PYTHON_VERSION: '3.11.5'
  PATH_TO_CONFIG: 'src.s3_platform_plugin_template'
  CONFIG_FILE: 'config.json'
  PLUGIN_NAME: 's3_platform_plugin_template'

permissions:
  contents: write

jobs:
  generate-and-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: S3 sync 2
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.MIRROR_TARGET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: ${{ secrets.S3_SERVICE_URL }}
        AWS_REGION: ${{ secrets.S3_REGION }}
        SOURCE_DIR: './'      # optional: defaults to entire repository
        DEST_DIR: ${{secrets.MIRROR_PATH}}${{env.PLUGIN_NAME}}
    - name: S3 Sync
      uses: peter-evans/s3-backup@v1
      env:
        ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        MIRROR_TARGET: ${{ secrets.MIRROR_TARGET }}
        STORAGE_SERVICE_URL: ${{ secrets.S3_SERVICE_URL }}
        AWS_REGION: ${{ secrets.S3_REGION }}
        MIRROR_SOURCE: ${{secrets.MIRROR_PATH}}${{env.PLUGIN_NAME}}
      with:
        args: --overwrite --remove
